### ISSUE TITLE
errors while starting houdini caused by MOPS

### ISSUE THREAD

**Issue by pilot3d** [toadstorm/MOPS#110]
I got following errors returned by console during stratup:of Houdini after installation of MOPS:
`opalias: 'mountain' is not a known operator.
opalias: 'ripple' is not a known operator.
opalias: 'pointmap' is not a known operator.
opalias: 'waveform' is not a known operator.
opalias: 'grainsource' is not a known operator.
opalias: 'baketexture' is not a known operator.
opalias: 'guidegroom' is not a known operator.
opalias: 'guidetransfer' is not a known operator.
opalias: 'guidedraw' is not a known operator.
opalias: 'guideprocess' is not a known operator.
opalias: 'guideinit' is not a known operator.
opalias: 'hairclump' is not a known operator.
opalias: 'hairgen' is not a known operator.
opalias: 'volumevelocityfromcurves' is not a known operator.
opalias: 'volumevelocityfromsurface' is not a known operator.
opalias: 'finiteelementsolver::2.0' is not a known operator.
opalias: 'pyrosolver::2.0' is not a known operator.
opalias: 'smokesolver::2.0' is not a known operator.
opalias: 'gasupres::2.0' is not a known operator.
opalias: 'flipsolver::2.0' is not a known operator.
opalias: 'popsolver::2.0' is not a known operator.
opalias: 'popwrangle' is not a known operator.
opalias: 'popcollisionbehavior' is not a known operator.
opalias: 'impactanalysis' is not a known operator.
opalias: 'attribblur' is not a known operator.
opalias: 'heightfield_quickshade' is not a known operator.
opalias: 'pxrfractalize' is not a known operator.
opalias: 'fit' is not a known operator.
opalias: 'volumeshadercore' is not a known operator.
opalias: 'brushedmetalshadercore' is not a known operator.
opalias: 'carpaintshadercore' is not a known operator.
opalias: 'skinshadercore' is not a known operator.
Warning: Bad operator type when binding handles: Object/path
Warning: Bad operator type when binding handles: Object/pathcv
Warning: Bad operator type when binding handles: Object/cop2plane
Warning: Bad operator type when binding handles: Sop/agentcollisionlayer
Warning: Bad operator type when binding handles: Sop/agentconfigurejoints
Warning: Bad operator type when binding handles: Sop/agentedit
Warning: Bad operator type when binding handles: Sop/attribwrangle
Warning: Bad operator type when binding handles: Sop/attribexpression
Warning: Bad operator type when binding handles: Sop/mountain::2.0
Warning: Bad operator type when binding handles: Sop/ripple::2.0
Warning: Bad operator type when binding handles: Sop/platonic
Warning: Bad operator type when binding handles: Sop/pointwrangle
Warning: Bad operator type when binding handles: Sop/split
Warning: Bad operator type when binding handles: Cop2/emboss`
```

**Comment by toadstorm** [comment]
Sounds like your houdini.env is not properly configured. Make sure your
HOUDINI_OTLSCAN_PATH always ends with @/otls, and isn't redefined later by
some other line. README.MD has detailed instructions on how to configure
your environment.

**Comment by toadstorm** [comment]
Did fixing your environment resolve the issue?

**Comment by johnnyquest** [comment]
I just ran into this at work (and totally forgot to configure the @/otls part) so it worked for _me_, thanks!! :D
