### ISSUE TITLE
Move Along Spline: Arc Length option doesn't respect Wrapping

### ISSUE THREAD

**Issue by profbetis** [toadstorm/MOPS#139]
I remember in my original tests it worked fine automatically so I know it's possible/easy so I think it must be something small.

**Comment by toadstorm** [comment]
this should work in the next build

**Comment by profbetis** [comment]
Seems that it only doesn't work with NURBs Curves. Very strange that it works just fine in Solver mode though.

**Comment by toadstorm** [comment]
there were some weird problems with attributes disappearing on NURBS curves due to conversion to polygons, and some of the arc length code mysteriously went missing from my wrangles. the latest release (v0.1.25e) seems to work on my end, including wrapping in either direction.

**Comment by profbetis** [comment]
Commit 6f204bb seems to have fixed this!
