### ISSUE TITLE
Solver falloff

### ISSUE THREAD

**Issue by sepux** [toadstorm/MOPS#155]
Hey Henry, 

What about a solver falloff, I'm using Mash here but you can have different mode in the falloff this is call "add" and is just a sim, just like a sopsolver, so the fall offs fade depending the time, etc make for nice smooth movements. it would be cool to add this functionality to MOPs let me know what you think and here is a Maya file so you see how it works.

Also I couldn't make just simple pts (I was using a popnet) as falloffs basically what Im showing Mash which the falloff is driven by particles. I tried to make it work in MOPs but the only way that I could if I use copy to points and use the MOPs_Object_Falloff, maybe I'm missing something. 

[Falloff_addSim.zip](https://github.com/toadstorm/MOPS/files/2777128/Falloff_addSim.zip)

![2019-01-20_14-50-08](https://user-images.githubusercontent.com/20706047/51446244-38957f00-1cc4-11e9-86b7-3d0db5fe353b.gif)

**Comment by toadstorm** [comment]
Okay, I'll add a "Point Cloud" option to the Object Falloff, though really all it's doing is acting as an Attribute Transfer from the source points. That'll go in the next build.

As far as fading attributes... I guess it's just a Solver SOP? I wonder if this is something that should be inserted into existing Falloff nodes, or created as a separate node that's a sort of very quick preset for a Solver SOP.

**Comment by toadstorm** [comment]
The catch here is that allowing each Falloff node to have its own internal Solver loop means that we'd need some kind of extra shelf tool or shortcut to force every upstream Falloff node to cook on demand, since otherwise every single node would have to be manually resimulated when upstream nodes are changed.

**Comment by sepux** [comment]
Oh yeah, that makes sense, then I guess it will be easier to add another node so you just apply the fade in the desire falloff.
