### ISSUE TITLE
RFE: Mops Reorient - Make orient from custom attrs

### ISSUE THREAD

**Issue by Solitudex** [toadstorm/MOPS#178]
There are cases where I want to create the orient, and instead of naming/renaming attrs it would be nice to just supply custom attr names for N and up in which to build the transform / orient data. In those cases, the second input is redundant, and shouldn't be required at all either.

**Comment by toadstorm** [comment]
This is resolved as of Experimental build 0.1.48 with the new MOPS Reorient 1.1.
