### ISSUE TITLE
MOPS Explode - Piece Attribute default is incorrect type ("name")

### ISSUE THREAD

**Issue by pixel-ninja** [toadstorm/MOPS#181]
The default for defining pieces by attribute is "name", which is almost always a string attribute.
This produces the undesired result converting the whole mesh into a single packed fragment, as it is looking for an integer not a string.

Two possible solutions I can think of:
- Change the default from "name" to "class". As this is the most common integer attribute used for this purpose
- Support strings by checking the attribute class and converting the value to an integer if it's a string attribute.

Putting this into the "define_initial_clusters" wrangle does the trick:
if(primattribtype(0, "`chs("piece_attribute")`") == 2){
        i@__cluster = random_shash(prim(0, "`chs("piece_attribute")`", @primnum));
    }else{
        i@__cluster = prim(0, "`chs("piece_attribute")`", @primnum);
    }

**Comment by pixel-ninja** [comment]
This is on v0.1.49 Experimental

**Comment by toadstorm** [comment]
Thanks for this! That works great. I'll incorporate this into the next build.

**Comment by toadstorm** [comment]
This fix is implemented as of 0.1.50 Experimental.
