### ISSUE TITLE
Transform Modifier - Pivot handling issue

### ISSUE THREAD

**Issue by pixel-ninja** [toadstorm/MOPS#183]
I think "Do Pivots" should be unchecked on the Apply Attributes node inside of the Transform Modifier.

Currently If the pivot has been changed then the Transform Modifier will shift the geometry by the inverse of that pivot. Even in default state, when no transforms have been applied.

This applies for primintrinsic pivot, v@pivot and MOPS_Align.

v0.1.49 Experimental

**Comment by toadstorm** [comment]
I can't recreate this on my end... do you mind posting a simple example .HIP that demonstrates the problem? Thanks!

**Comment by toadstorm** [comment]
Okay nevermind, I got this. 0.1.51 Experimental includes this fix, thanks for reporting it!
