### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by emilsvfx** [toadstorm/MOPS#194]
on Houdini 17.5.293  ,Houdini 17.5.258 gives me this error.  it`s not updating.

![houdini_2019-06-29_14-18-50](https://user-images.githubusercontent.com/22729351/60383610-c8153a00-9a7b-11e9-8c59-7d66dd2d8ae2.png)

**Comment by toadstorm** [comment]
This is a known bug with a slightly older build of MOPs... try downloading
the latest version and installing manually.
