### ISSUE TITLE
Noise Falloff - Inaccurate Octave Math

### ISSUE THREAD

**Issue by profbetis** [toadstorm/MOPS#207]
Adjusting the octave and roughness parameters on the noise changes the overall amplitude of the effect powerfully. 

The current noise setups are very custom and probably difficult to change to be mathematically consistent and correct. I suggest swapping out custom VEX noises for an Attribute Noise wrapper which will yield predictable results. Perhaps the noises not implemented in Attribute Noise can remain so that the two can co-exist.

**Comment by toadstorm** [comment]
This was just a weird order of operations problem that looks like it's existed since release! This is patched up in `henry_dev`... I'll add it to the next Experimental release once I finish the Instancer update.
