### ISSUE TITLE
Amplitude not working on the latest henry_dev

### ISSUE THREAD

**Issue by sepux** [toadstorm/MOPS#210]
in the latest henry_dev, the amplitude isn't having an effect on the noises. This happens in all falloffs

![PSImYHYyIg](https://user-images.githubusercontent.com/20706047/64903315-08dc2280-d66b-11e9-8728-58abe1b5e4dc.gif)

**Comment by toadstorm** [comment]
Thanks for catching that Sepu... this is fixed as of 0.1.67 Stable.
