### ISSUE TITLE
MOPs_Instancer is not forwarding pscale?

### ISSUE THREAD

**Issue by AtomicPerception** [toadstorm/MOPS#213]
I mentioned this on the mops board, but I thought I'd drop it in here, as well.
pointwrangle2 & pointwrangle3, inside the MOPs_Instancer are not forwarding pscale.

Here is my suggested code fix, which worked on @xcaseyx HIP file using mops 0.1.67.
```c
//Detect additional attributes to forward.
int exists = haspointattrib(1, "pscale");
if (exists) {f@pscale = primuv(1, "pscale", @ptnum, uv);}
exists = haspointattrib(1, "Cd");
if (exists) {v@Cd = primuv(1, "Cd", @ptnum, uv);}
```

**Comment by toadstorm** [comment]
This should be patched in Instancer 1.3... sorry about the late response, still trying to clean everything up for the next stable release. Please let me know if this is still an issue in the latest build.
