### ISSUE TITLE
Package instal not working.

### ISSUE THREAD

**Issue by NicTanghe** [toadstorm/MOPS#255]
Installing via github  packages folder not working.
qLibb working without issues.

Does the json file not just need an otlscanpath ?
![image](https://user-images.githubusercontent.com/13624265/83358422-b1562200-a373-11ea-8b7d-7787a4375e6d.png)
* capitalizing users did not help
* removing extra comma also did not help.

**current Code**
```
{
	"env": [
		{
			"MOPS": "C:/Users/Tanghe/Documents/houdini18.0/packages/MOPS"
		},
	],
	"path": "$MOPS"
	
}
```

**Comment by toadstorm** [comment]
QLibs uses a more specific set of installation variables because of how it
separates its OTLs into "base", "future", etc. Try placing the MOPs
directory anywhere other than inside $HOME/houdini18.0 directory, and
update the package file to match.

**Comment by NicTanghe** [comment]
Following code/ location also did not work.
```
{
	"env": [
		{
			"MOPS": "C:/Users/Tanghe/Documents/dev/Houdini/MOPS"
		},
	],
	"path": "$MOPS"
	
}
```

**Comment by toadstorm** [comment]
Okay. The path that you're defining there... is that the exact parent directory of the folders "otls", "scripts", and all that?

Also, how are you testing if the installation worked? What context are you creating nodes in?

**Comment by NicTanghe** [comment]
It's the exact path : 
![image](https://user-images.githubusercontent.com/13624265/83398575-e314ca80-a3ff-11ea-93b2-3d804be20265.png)

im opening them in geo.
![image](https://user-images.githubusercontent.com/13624265/83398694-22dbb200-a400-11ea-8c42-eab326b9d7ce.png)

**Comment by NicTanghe** [comment]
Oh i neede to make some actual geometry first srry for the trouble
