### ISSUE TITLE
Add Links to Readme

### ISSUE THREAD

**Issue by melMass** [toadstorm/MOPS#261]
I must be dumb but I can't find the MOPs forum?

I found the website (motionoperators), but not the board.
I think both links should be added to either the readme or the description of the repo :)

**Comment by toadstorm** [comment]
The forums are linked from the main website; they're at [https://forum.motionoperators.com](https://forum.motionoperators.com).

I'll add a link to the README.MD.

**Comment by melMass** [comment]
Subscribed! Thanks
