### ISSUE TITLE
MOPS delay, breaks instancing.

### ISSUE THREAD

**Issue by larrybrit** [toadstorm/MOPS#264]
Hey Henry, I was using a mops instancer to scatter and randomize points. No direct instances, just points creation. Those points were then used to instance rs proxies via the instancefile method. All is well until I add a mops delay node. The instances disappeared. After doing some light digging, I found the issue lies with the "remove spare attributes" node within mops delay. disabling it fixes the issue. But it's a bit brutish of a fix :)

using the latest 1.1.7e version. on h18.0.499

**Comment by toadstorm** [comment]
Ah, I think this thing is expecting that the intrinsics will have all the correct information... it's not expecting point instances. Let me test a few things and see what I can do about safely keeping attributes.

**Comment by toadstorm** [comment]
Okay, I've added this change to the `henry_dev` branch if you're interested in testing it.

**Comment by larrybrit** [comment]
Thanks Henry! I'll have a go at it over the weekend.

**Comment by larrybrit** [comment]
It fixes my issues. Thanks!
