### ISSUE TITLE
Mops Randomize ignoring local orient

### ISSUE THREAD

**Issue by pixel-ninja** [toadstorm/MOPS#272]
I noticed that mops randomise was ignoring local mode.

The primitives I was using had the mops_orient attribute set but the "transform" intrinsic was default.
Adding this line to the "randomize_P" wrangle solves this in my case (at least for position):
translate = qrotate(p@mops_orient, translate);

As an aside is there a mops function for properly applying a quaternion (i.e. mops_orient or orient) to the transform intrinsic? In effect, setting the pivot rotation. If not it seems like something that could be added to Mops Align.

**Comment by toadstorm** [comment]
Nice catch! I forgot to rotate the offset vector in the case of mops_orient.

The node you're looking for is MOPs Reorient. Give it a quaternion attribute and it'll use that as the rotation axes from then on. It doesn't actually change the intrinsics; there doesn't seem to be a way to reset the axes of orientation and keep the primitives from visibly moving without unpacking, and that's really slow.

I'll patch this out shortly, thanks again!

**Comment by toadstorm** [comment]
This patch is live in the `henry_dev` branch.

**Comment by pixel-ninja** [comment]
Awesome. That was quick.
Cheers!

I'll check out reorient, thanks again :)
