### ISSUE TITLE
Mops convert rest frame

### ISSUE THREAD

**Issue by pixel-ninja** [toadstorm/MOPS#274]
Hey. I noticed the other day that the rest frame in mops convert isn't hooked up to "timeshift2".
It's set to $FSTART.

I only noticed because I was doing some post sim work with mops and the convert kept telling me that the frame didn't exist in my cache.

**Comment by toadstorm** [comment]
Nice catch! Thanks for pointing that out. I've patched this in the `henry_dev` branch.
