### ISSUE TITLE
Move Along Spline error on 18.5

### ISSUE THREAD

**Issue by dpotuznik** [toadstorm/MOPS#275]
Hi,

thank you for your amazing tool for houdini.

i just try today on Houdini 18.5 on your demo file Move_Along_Spline_offset.hip
work on houdini 18.0

Error 
Invalid source /obj/osf_qrcodeDataLight1/MOPs_Move_Along_Spline/apply_new_goals/attribvop1
Error: Vex error: Unable to load shader 'op:/obj/osf_qrcodeDataLight1/MOPs_Move_Along_Spline/apply_new_goals/attribvop1'. 

Have nice day.
Best Regards,
Daniel

edit:
i open the node and on the attribute wrangle "Apply_new_goal"

i change on 3 error 
goalu = primuvconvert(@OpInput2, goalu % arclen, i@__curvenum, 10)[0]; 
to
goalu =  vector2(primuvconvert(@OpInput2, goalu % arclen, i@__curvenum, 10))[0]; 
and it work again.

**Comment by toadstorm** [comment]
Nice catch. I just pushed an update to the `henry_dev` branch that fixes this. Thanks for reporting!
