### ISSUE TITLE
Delay seems to be broken when used with groups

### ISSUE THREAD

**Issue by thebrokemonkey** [toadstorm/MOPS#287]
Been using MOPS a lot over the last few weeks and loving it. However, when having a string of multiple objects (MOPS convert from packed but also a problem when using the MOPS instancer) with falloff, then transform and randomize modifiers, and then trying to delay a selection (via groups) of the instances, it tends to mess up some of or all the instances. (Weird rotations etc). The only way I was able to make it work is by delaying all the objects and then blasting all the unwanted objects and then merging them back into the main stream. In Houdini 18.5.351 with MOPS v1.3.

Here a video of the problem and the file:
https://drive.google.com/drive/folders/1NjvRbnAoEDKVlNMV1z8H19RJiGtWaey4?usp=sharing

**Comment by toadstorm** [comment]
Nice catch! Dumb mistake on my part, was re-assigning transforms based on the wrong attribute. This should be patched in the `henry_dev` branch if you want to test it out.

**Comment by thebrokemonkey** [comment]
Amazing! Thank you for your hard work!

**Comment by antoniopepe82** [comment]
Great . Thanks man
