### ISSUE TITLE
MOPS Warnings at Scene Opening

### ISSUE THREAD

**Issue by DaBaptisteFraboul** [toadstorm/MOPS#340]
Hello, 👋

I have a problem when opening houdini scenes with MOPS nodes. 

I created a basic setup with a `rubber_toy` and a `mops_instancer`.
When I save and repopen the `.hip` file, the following message pops up (_Here is the complete log [MOPS_log.txt](https://github.com/user-attachments/files/16350863/MOPS_log.txt)_ ):

![image](https://github.com/user-attachments/assets/a9c93dd5-676c-46a4-a784-bd8e1af0282d)

I did search throught the discord, the forum and the former issues on Github but could not find similar bug🔎🐛. 

I am currently using **Houdini FX 18.5.759 on Windows**.
 
I installed Mops using the `Houdini.env` method as suggested in the Readme.md. 
I tried both `master` and `experimental` branches but I keep getting the error on opening. 

Do you have any idea about what could be happening🕵️‍♂️ ?

**Comment by DaBaptisteFraboul** [comment]
Thanks you for your answer, 

It doesnt cause any trouble to the scene beside the warnings when loading. 

I will test with a Houdini version> 19.0

**Comment by toadstorm** [comment]
Checking in on this ticket... are you still seeing warnings in H19?

**Comment by DaBaptisteFraboul** [comment]
Hi, 
I couldn't get my hand on Houdini > 19.0, 
however I think we can close this issue to. 

We will switch to the latest version of houdini later, I will reopen the issue if we'll tumble on those warnings at this moment. 

Thank you very much for your help.✨

**Comment by toadstorm** [comment]
Okay, thanks for the reply! Closing this one.
