### ISSUE TITLE
cant install MOPS ;(

### ISSUE THREAD

**Issue by PaulSue** [toadstorm/MOPS#341]
Hi tried, various locations, nothing works;
created a folder on my "C drive, MOPS/MOPS.json, 
user/cpz/documents/houdini20.0/packages/MOPS.json, and  user/cpz/documents/20.0/packages/MOPS.json,
Im at a loss, please help ;(

**Comment by toadstorm** [comment]
The path of the JSON file needs to be in the Houdini packages folder for your installation of Houdini. If you're on Windows, this is going to be in your Documents folder, /Houdini20.0/packages/MOPS.json. 

Once you have the file placed in that location, you need to edit the file and change the value of the MOPS variable to the path where you extracted the MOPS files to. This should be somewhere else on your drive, not in the packages folder itself. Make sure the path is using forward slashes and not backslashes, which are standard on Windows. For example, if you extracted MOPS to C:\Users\cpz\MOPS, you would change the value of the MOPS variable in the JSON file to C:/Users/cpz/MOPS.

Detailed installation instructions are available here: [https://github.com/toadstorm/MOPS/wiki/Installation](https://github.com/toadstorm/MOPS/wiki/Installation)

**Comment by PaulSue** [comment]
Thanks but still nothing; do I need to “uninstall” locations that didn’t work?  I have  tried, "MOPS": C:"/Users/cpz/packages/MOPS", and , "MOPS": "C:/Users/cpz/Documents/houdini20.0/packages/MOPS.", I am at a loss ;(

**Comment by PaulSue** [comment]
BTW, my Houdini folders, are in Program files/Side Effects Software/Houdini 20.0.653/packages/mops_version.json

I took the mops_version.json file and made a folder on my “C” drive, called Mops, edited it,  placed the file in there,  changed the value to, "MOPS": C:"/Users/cpz/packages/MOPS", are my mistakes clear to you? Im sorry to bother you, and waste your time, but I want to get this right so I can proceed with your course, Craig

**Comment by toadstorm** [comment]
What is this?

**Comment by PaulSue** [comment]
![Uploading CZ_python_shell.png…]()

**Comment by PaulSue** [comment]
my python shell, I  thought, if you dont recognize it, then pleas tell me what I did wrong

**Comment by toadstorm** [comment]
Whatever you posted there looks like CSS, it's not Python.

You need to open Houdini's Python shell, and run the following code: 

```import os
print(os.environ.get("HOUDINI_PATH"))
```

This should print out a list of paths where Houdini is looking for packages. I need to see that list to verify that Houdini is looking for a MOPS installation directory.

**Comment by PaulSue** [comment]
I believe thas this is it
<img width="665" alt="CZ_HOUDINI_SHELL" src="https://github.com/user-attachments/assets/364cf5da-ea35-458e-9914-ab1b504b52a1">

**Comment by toadstorm** [comment]
Okay, that upload worked. 

You see how in that list of paths, there's one pointing to C:/Users/Henry/Projects/VFX/MOPS? That's the default example path that's included in the JSON file that you placed in your packages folder. You need to edit that JSON file, and replace the reference to that path with the actual path you extracted MOPS to on your system, and remember to use forward slashes in place of backslashes.

**Comment by PaulSue** [comment]
Thanks Henry, but I already did this, didn't I?
<img width="851" alt="this-is-what-I-did" src="https://github.com/user-attachments/assets/65e4483f-607b-475b-97e2-a870915d0824">

**Comment by toadstorm** [comment]
If you read the instructions, you'll note that you definitely **do not** want to install MOPs to an existing Houdini system directory, and the package file should be in Documents/Houdini 20.0/packages, not in the Houdini built-in packages directory. You need to remove that JSON file and move MOPs somewhere else outside of any existing Houdini installation, then update the JSON file _in the correct packages path_ to reflect the new installation path of MOPs. 

Please read the instructions I provided carefully, or watch the video I linked you to. Every mistake you made during the installation process is documented there.

**Comment by PaulSue** [comment]
I feel like giving up henry; either I’m too obtuse, not famialr with the lexicon, or what ever-please see attached, I removed the MOPS file have an unzipped folder in my “C” drive, and this is the only MOPS.json where you suggeste, what am I doing wrong here?

**Comment by toadstorm** [comment]
I don't see the attachment, can you please verify that you've included one?

**Comment by PaulSue** [comment]
Yes of course; knowing how computer-tech-lame I am, I must have removed a file, now I can not even open, version, 653, and 547, but 20.5.278 I can -this is what I was afraid of, please see attached, thank you

**Comment by toadstorm** [comment]
There is still no visible attachment.

**Comment by PaulSue** [comment]
Thanks, but I’ve tried many, many times, and it is not working for me. Curious, if we spoke on the phone in order to help me, what would this cost?, thank you Craig

**Comment by toadstorm** [comment]
Contact me at henry@motionoperators.com and we'll schedule a Zoom call. Closing this ticket as it's not bug-related.
