### ISSUE TITLE
MOPS Shape Falloff handle visualizers do not display in LOPS viewport (SOPS subcontext)

### ISSUE THREAD

**Issue by ariffjeff** [toadstorm/MOPS#342]
For example, the spherical falloff type that would otherwise display the wireframe sphere visualizer for the falloff of the MOPS Shape Falloff node in the OBJ/SOPS context, will fail to display in LOPS/SOPS (inside a SOP Create LOP). This therefore just leaves the user with the default transform handles and make it difficult to identify where the falloff is in the viewport.

MOPS in general seems to still work regardless of this fact.

**Comment by toadstorm** [comment]
This appears to be a Houdini bug specific to Houdini 20.5. In Houdini 20.0 the handles are visible even inside a SOP Create. I'd recommend filing this with SideFX as an RFE.

**Comment by ariffjeff** [comment]
Will do, thanks!
